# Generated by Django 5.2.17 on 2026-09-22 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn')),
                ('name', models.CharField(max_length=150, verbose_name='Tên môn')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='Số tín chỉ')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã lớp học phần')),
                ('lecturer', models.CharField(max_length=120, verbose_name='Giảng viên')),
                ('room', models.CharField(max_length=30, verbose_name='Phòng')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(2, 'Thứ 2'), (3, 'Thứ 3'), (4, 'Thứ 4'), (5, 'Thứ 5'), (6, 'Thứ 6'), (7, 'Thứ 7')], verbose_name='Thứ')),
                ('start_period', models.PositiveSmallIntegerField(verbose_name='Tiết bắt đầu')),
                ('end_period', models.PositiveSmallIntegerField(verbose_name='Tiết kết thúc')),
                ('max_students', models.PositiveIntegerField(default=50, verbose_name='Sĩ số tối đa')),
                ('semester', models.CharField(default='2026-2027 HK1', max_length=30, verbose_name='Học kỳ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course')),
            ],
            options={
                'ordering': ['weekday', 'start_period', 'code'],
            },
        ),
    ]
